apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acse-policy-gui
  labels:
    app: acse-policy-gui
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - acse
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
