apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: acse-policy-gui-subscription
  labels:
    app: acse-policy-gui
spec:
  channel: acse-policy-gui-entitlement/acse-policy-gui-channel
  placement:
    placementRef:
      name: acse-policy-gui--placement-rule
      kind: PlacementRule
