apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: ibm-local-charts
spec:
    pathname: https://icp-console.spx-mcm-cluster-9cb7e5637afa55ea707aef0b31c19bc5-0000.eu-de.containers.appdomain.cloud:443/helm-repo/charts
    configRef:
      name: insecure-skip-verify
    type: HelmRepo
---
apiVersion: v1
data:
  insecureSkipVerify: "true"
kind: ConfigMap
metadata:
  name: insecure-skip-verify
