apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: service-acse-nginx
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: acse-nginx
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: nginx-service
      labels:
        acse-frontend: "true"
    spec:
      selector:
        app: acse-nginx
      ports:
        - name: http
          port: 9080
          targetPort: 9080    
